### ISSUE TITLE
level up  write stream does not pause which leads to bad leaks/failed data imports

### ISSUE THREAD

**Issue by soldair** [rvagg/node-levelup#107]
here is a reduced test case that at least can simulate the leak.
https://gist.github.com/soldair/5225603

if you move the data generation out of process and read from stdin transformed into objects at some point everything locks up. this could be related to node internally competing for uv 

@rvagg said on twitter "we probably need to emit ‘pause’ when there are a certain number of ops in progress; perhaps 4 to match libuv threads."

i can't right now but i may be able to submit a pull request tonight.

**Comment by ralphtheninja** [comment]
Closing this because write-stream will be removed in `1.0.0`
