### ISSUE TITLE
writeStream.write callback

### ISSUE THREAD

**Issue by pgte** [rvagg/node-levelup#161]
When using a write stream, [the Node spec](http://nodejs.org/api/stream.html#stream_writable_write_chunk_encoding_callback_1) says that you can pass in a callback as last argument like this:

```js
var ws = db.createWriteStream();
var o = {key:'k1', value: 'v1'};
ws.write(o, function() {
  console.log('wrote', o);
});
```

I don't need the the write stream interface to be 100% compliant, but I do need to get write acknowledges, which the current implementation does not provide.

I looked at the source code and I couldn't find an obvious way around this (except for reimplementing the write stream on top of `db.put` and `db.del`, but I didn't want to go that way). 

For instance, is there any event that is emitted after a flush? I was looking at the `drain` event emitted [here](https://github.com/rvagg/node-levelup/blob/master/lib/write-stream.js#L134), but I think that [`_writeBlock` is not always `true`](https://github.com/rvagg/node-levelup/blob/master/lib/write-stream.js#L53), so I can't trust that, can I?

**Comment by ralphtheninja** [comment]
@pgte Closing this because write-stream removal in 1.0.0
