### ISSUE TITLE
read/write stream incompatibility

### ISSUE THREAD

**Issue by juliangruber** [rvagg/node-levelup#181]
As of level@0.15.0, this fails:

```js
var db = level(__dirname + '/db');
db.createReadStream()
  .pipe(db.createWriteStream())
  .on('close', console.log.bind(console, 'close'));
```

Nothing is logged. It doesn't depend on whether the db is empty or not. The snippet works with level@0.14.0.

**Comment by ralphtheninja** [comment]
@juliangruber Can we close this or do you want to keep it open?

**Comment by juliangruber** [comment]
since there's no write stream any more, let's close :)
