### ISSUE TITLE
WriteStream slowdown after ~3 million records

### ISSUE THREAD

**Issue by gmaclennan** [rvagg/node-levelup#185]
I am experimenting with importing OSM XML files into levelDB and indexing with Quadtrees.

https://github.com/digidem/leveldb-osm/tree/xml-stream

It is very fast for small extracts. But when I try to import the latest germany.osm extract, it starts at about 16,000 records per second, but at about 3,000,000 records it begins to slow down massively and suddenly to about 100 records / second.

I could be my code, this is my first experiment with leveldb (I like it).

I was using node-big-xml first, then switched to xml-stream and it did improve things slightly - but just delayed the slow down.

Is this a problem with Leveldb or how streams are interacting?

**Comment by ralphtheninja** [comment]
Closing this because write-stream will be removed in `1.0.0`.

@gmaclennan Let us know if this is still an issue by reopening this issue or we can open a new issue on appropriate write-stream implementation
