### ISSUE TITLE
Bite the bullet and remove WriteStream completely?

### ISSUE THREAD

**Issue by rvagg** [rvagg/node-levelup#199]
WriteStream is only there for the sake of symmetry but that's not a great reason in itself if there are better reasons for it not to be there. I think we're starting to realise that there are different use-cases that require different implementations and we're already seeing some alternative implementations so why not set them free to coexist and compete in user-land?

Discuss

If we conclude that it should be removed then we can add documentation to the ReadStream section saying that if you want a WriteStream then go to a particular place on the wiki to see a list of implementations and what they are good for. We could even dedicate a whole wiki page to this if need be.

if we concluded that it should stay, then I'll try and get these competing pull requests for new WriteStreams reconciled and sort something out because having a streams2 ReadStream and a streams1 WriteStream is a mess and this needs to be resolved.

**Comment by ralphtheninja** [comment]
It seems concensus have been reached on removing write-stream. Closing.

**Comment by loveencounterflow** [comment]
The one missing thing here for someone who has done streaming with NodeJS but is still puzzled over the alternatives is a discussion what the strengths and weaknesses of some WriteStream implementations are and what to look out for. Any pointers?
