### ISSUE TITLE
Open Error: IO error Invalid argument

### ISSUE THREAD

**Issue by caio-ribeiro-pereira** [rvagg/node-levelup#222]
Hi, this is my first time using and learning about LevelDB with Node.js, and my simple app, can't run, this is my simple code:

``` javascript
var
  level = require('level'),
  express = require('express'),
  uuid = require('node-uuid'),
  db = level('./users.db', {valueEncoding: 'json'}),
  app = module.exports = express();

app.use(express.logger('dev'));
app.use(app.router);

app.get('/users', function(req, res) {
  db.get('users', function(err, users) {
    if (err) return res.json(404, err);
    return res.json(200, users);
  });
});

app.post('/user', function(req, res) {
  db.put('users', req.body.user, function(err) {
    if (err) return res.json(404, err);
    return res.json(200);
  });
});

app.listen(5000, function() {
  console.log('LevelDB API running on port 5000');
});
```

And when I run: node app
It throws the error:

`OpenError: IO error: ./users.db/MANIFEST-000001: Invalid argument`

I am using latest stable: Node.js 0.10.23

Does anybody can help me? Thanks!

**Comment by olalonde** [comment]
I had the same problem running bitcoind (which uses leveldb) in a mounted folder with boot2docker. Fixed it by mounting the folder with nfs instead of vboxfs and wrote a script to do the switch automatically: https://gist.github.com/olalonde/3f7512c0bd2bc8abb46d

**Comment by eugeneware** [comment]
Great news everyone (/cc @groundwater), the latest version of docker (you can register for at https://beta.docker.com/) which does **NOT require virtualbox** (uses xhyve under the hood - with the native hypervisor that comes with OS X) - doesn't suffer from this `mmap` bug. You can happily create databases on your OS X host operating system, and volume map them to the xhyve docker host and it works beautifully! Woo!

You can read more about the new docker [here](https://blog.docker.com/2016/03/docker-for-mac-windows-beta/)  and get the full docs [here](https://beta.docker.com/docs/)

It is a glorious day!

**Comment by Zoltu** [comment]
Not sure if anyone is watching this anymore, but I am experiencing similar symptoms running Docker for Windows beta.  I have an Ubuntu image that does some LevelDB stuff (not sure what exactly as its third party) and I get this error:
```
events.js:141
      throw er; // Unhandled 'error' event
      ^
OpenError: IO error: /data/farmdata/farmer.db: Invalid argument
    at /usr/lib/node_modules/storjshare-cli/node_modules/storj/node_modules/levelup/lib/levelup.js:119:34
    at /usr/lib/node_modules/storjshare-cli/node_modules/storj/node_modules/leveldown/node_modules/abstract-leveldown/abstract-leveldown.js:39:16
```

In the Windows host I see `farmdata/farmer.db` folder in the folder I mounted to `/data`, and it even has some files in it (mostly log files, but also some other stuff like `CURRENT`, `LOCK`, `LOG`, `MANIFEST-000001` (I'm not sure if these are LevelDB files or the app's).

Windows for Docker uses Windows Hyper-V to run a Moby Linux VM which acts as the host OS for the docker client.  The Windows volume is therefore mapped to the Moby Linux VM which I then mount with `docker run -v //d/foo:/data`.

**Comment by eugeneware** [comment]
I don't run windows, but it could be that `mmap()` doesn't work correctly under the windows bash emulation. You can try compiling and running this file against a file on your file system to see if mmap works or not

https://gist.github.com/0d991472c71409f5cdf0ed7aeb4e6222

**Comment by Zoltu** [comment]
I don't believe bash is being emulated in this scenario.  I believe Moby Linux is being virtualized (by way of hypervisor) and then it is running a docker host which is in turn running a docker container which is running the code.  That being said, I'll do a bit of googling to see if I can find any outstanding problems with `mmap` on docker for windows.  There is a lot of stuff out there about VirtualBox and `mmap`, but nothing I can find for the new stuff.

Also, I don't currently have a setup that would let me easily compile/run that gist in Windows.  :/

**Comment by eugeneware** [comment]
I've wrapped everything into a docker image so you can test. Check out the details [here](https://github.com/eugeneware/mmap)

**Comment by Zoltu** [comment]
Both tests passed:
```
PS C:\Users\Micah> docker run --rm -it eugeneware/mmap
hello
world
mmap works from internal filesystem - hoorah!
PS C:\Users\Micah> docker run --rm -it -v //d/mmap/local.txt:/app/test.txt eugeneware/mmap
test mmap file
```

**Comment by eugeneware** [comment]
Hmm. Not sure what it could be. Most likely not an `mmap()` issue then which is the focus of this issue thread. I'd open up a new issue with some clear steps and code to replicate the issue.
