### ISSUE TITLE
Allow put/write of empty values

### ISSUE THREAD

**Issue by ggreer** [rvagg/node-levelup#223]
As silly as it sounds, I'd like to be able to save empty values to leveldb. Right now, I get "WriteError: value cannot be an empty String" if I try.

I traced the code back to the LD_STRING_OR_BUFFER_TO_SLICE macro in leveldown: https://github.com/rvagg/node-leveldown/blob/master/src/leveldown.h#L45

This macro is correct for validating keys, but leveldb allows for empty values. If this is not intentional behavior, I think I'll try to fix it and submit a pull request.

**Comment by ralphtheninja** [comment]
@ggreer What @kesla mentioned before is now in the `1.0.0-wip` branch (https://github.com/rvagg/node-levelup/commit/36658a2c7d7b5657c89af5f73b218496859088bb) so you'll have this functionality once `1.0.0` of `levelup` has been released.
