### ISSUE TITLE
WriteStream: do not emit close until the callback

### ISSUE THREAD

**Issue by dominictarr** [rvagg/node-levelup#247]
'close' should not be emitted until everything is confirmed written.
This is analogous to the behavior of the file system: the file is not closed until after it's accepted all the writes - and it means that what has been written should be readable - and I think that post events (put, batch, del) should have fired already.

this line needs to move into the callback (of course there is a bit more state to check, but basically) Otherwise, it's not possible to know when a write stream has successfully written everything to the database.

https://github.com/rvagg/node-levelup/blob/master/lib/write-stream.js#L149

this may also affect userland write streams... @Raynos @pgte @mcollina 
(it did those that I tried)

I do have write stream that behaves correctly, if you use pull-level with pull-stream-to-stream.

https://github.com/dominictarr/level-datablobs/blob/master/test/index.js#L45-L47

I will put in a pull request, but am too busy right now.

**Comment by ralphtheninja** [comment]
Closing this because write-stream will be removed in `1.0.0`
