### ISSUE TITLE
OpenError: Corruption: no meta-nextfile entry in descriptor

### ISSUE THREAD

**Issue by duluca** [rvagg/node-levelup#281]
I'm getting the following error in trying to host Level on Modulus.io. It somehow sometimes magically fixes itself, but I've no idea what might be the cause of this error?

INFO: Starting application.
Server started at: http://0.0.0.0:8080

events.js:72
        throw er; // Unhandled 'error' event
              ^
OpenError: Corruption: no meta-nextfile entry in descriptor
    at /mnt/data/1/node_modules/level/node_modules/level-packager/node_modules/levelup/lib/levelup.js:114:34
[2014-09-15T16:00:59.995Z] Failed to start application.

**Comment by doowb** [comment]
@duluca did you ever find a solution to this?

**Comment by ralphtheninja** [comment]
@duluca Which version of `levelup` are you using?

**Comment by doowb** [comment]
I'm using the latest of everything:

```json
"level": "^0.18.0",
"level-party": "^1.0.1",
```

I'm thinking it's a filesystem issue. Using `level-party`, I try a connection, then run a `get` and the response just hangs.

Like @duluca I'm able to get it to run when using their local storage, but that's not good for persistent data.

**Comment by duluca** [comment]
I've resolved the issue a few days after posting here. I forgot to close this out. 

If you store your level instance under the path defined by *process.env.APP_DIR* by Modulus, it works beautifully, even in auto-scaling situations, for persistent data storage. 

The data we're handling isn't critical, so a quick & dirty locking mechanism keeps things working.

**Comment by doowb** [comment]
I don't get the error any more when using `process.env.APP_DIR` but it's still not using the same database. I scaled out to 3 servers and each one has different data.

I don't know enough about files systems to know if modulus is using a type of attached storage that can't be accessed through leveldb or if there's a different issue that can be fixed within the node libraries.

**Comment by jcrugzz** [comment]
@doowb unless they are using some attached network storage based thing for sharing that `fs` with all 3 servers that seems expected.

**Comment by doowb** [comment]
@jcrugzz sorry, I thought it was mentioned above but it wasn't. They do offer a persistent storage option and expose `process.env.CLOUD_DIR` to get to it. Using `fs` to read and write files works fine. I'm assuming, like you said, that whatever layer is used is stopping leveldb from keeping a file descriptor open (or whatever the terminology is :wink:).

Has anyone else used a shared storage area for leveldb, with any provider? Also, if someone has any suggestions on what to search for on stackoverflow, I could move this discussion.

**Comment by duluca** [comment]
@doowb How are you able to confirm each instance having different data? I'm now thinking my testing methodology was inherently flawed. I've looked all over for another provider, but couldn't find a provider where data would persist across deployments.

**Comment by doowb** [comment]
You can direct a request to the specific servo by appending `?x-mod-servo={GUID}`. I view the source on the modulus logs dashboard to get the servo ids from the servo select list. Also, if you stop the servos and start them up again, the data in `process.env.APP_DIR` is gone.

**Comment by duluca** [comment]
@doowb Ok, I'll try that out, thanks. Yes, server goes away when you stop, but you can re-deploy without stopping the servo. But it is clear I've got some testing to do.

**Comment by doowb** [comment]
@duluca fyi... I created a `multilevel` server in EC2 backed by an ESB to keep the data persisted. I can connect to that from all my servos on modulus.

**Comment by duluca** [comment]
@doowb That is fantastic work!
