### ISSUE TITLE
leveldown version compatibility check failure

### ISSUE THREAD

**Issue by kendallsvp** [rvagg/node-levelup#297]
We're using dynalite which has a dependency on levelup.  Currently, our levelup is at the latest version 0.19.  At runtime, the version check is failing in lib/util.js, L59-L66.  I believe this is due to leveldown 1.0 being considered incompatible.

To workaround, we've commented out the above lines as per this thread:  https://github.com/rvagg/node-levelup/issues/282

My understanding is that when levelup 1.0 is released, this will fix the issue.

Is my understanding correct?  If so, is there a timetable for release?

Thanks.

**Comment by mhart** [comment]
Hey, author of dynalite here, sorry I didn't see this sooner – this was my bad, I shouldn't have updated the optional dependency of leveldown to 1.0 without checking it's compatibility with levelup first.

I fixed it in response to this issue:

https://github.com/mhart/dynalite/issues/20

@rvagg feel free to close this issue if you like, it was really a dynalite problem.
