### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by ralphtheninja** [rvagg/node-levelup#301]
Do we need to change anything in `node-levelup` in order to make it work with `node-leveldown@1.0.1`?

It would be nice to release a new version of `node-levelup` -> so `level-packager` can be updated -> so `level` can be updated as well.

/cc @rvagg

**Comment by rvagg** [comment]
This is causing too much pain for everyone, including me. I'm going to abort on the remove-writestream changes that are currently blocking and we'll do a levelup@1.0.0 with what's currently in that branch I think, I'll _try_ and propose a tip for that today and we can get agreement on release.

**Comment by ralphtheninja** [comment]
I'm trying out `levelup` with `leveldown@1.0.0` right now and have some failing tests. I could take a look and try to solve them if you like. You would probably do it quicker than me though, but I'd like to get more involved into this project now so it would be good practice for me.

**Comment by ralphtheninja** [comment]
For some reason this doesn't throw exception (in `test/batch-test.js`):

```js
assert.exception(this.batch.put.bind(this.batch, 'foo1'), function (err) {
  console.log('err.name', err.name, 'err.message', err.message)
  if (err.name != 'WriteError')
    return false
  if ('value cannot be `null` or `undefined`' != err.message)
    return false
  return true
})
```

But this clearly throws exception:

```js
var levelup = require('./')
var db = levelup('dbb')
var batch = db.batch()
batch.put.bind(batch, 'foo1')()
```

**Comment by ralphtheninja** [comment]
Oh, I suspect this is related to abstract-leveldown not throwing an error if the value is not defined in a batch.put operation. I'm sure @rvagg knows exactly why this is happening.

**Comment by ralphtheninja** [comment]
Think I understand why this is happening now. Feel free to correct me.

In `abstract-chained-batch.js` from `abstract-leveldown@2.0.3`

```js
AbstractChainedBatch.prototype.put = function (key, value) {
  this._checkWritten()

  var err = this._db._checkKey(key, 'key', this._db._isBuffer)
  if (err)
    throw err

  if (!this._db._isBuffer(key)) key = String(key)
  if (!this._db._isBuffer(value)) value = String(value)

  if (typeof this._put == 'function' )
    this._put(key, value)
  else
    this._operations.push({ type: 'put', key: key, value: value })

  return this
}
```

We no longer throw an exception if value is `undefined` or `null`, since that was removed in this commit: https://github.com/rvagg/abstract-leveldown/commit/66254dfaec7f2ed996179f77ba139a2298f8abdc

@rvagg Should these failing tests in `node-levelup` be removed or altered? I guess you had a reason for not throwing errors for these values.

**Comment by ralphtheninja** [comment]
Updated `node-leveldown` and tests here https://github.com/rvagg/node-levelup/pull/302
