### ISSUE TITLE
npm install fails with io.js

### ISSUE THREAD

**Issue by ralphtheninja** [rvagg/node-levelup#304]
This is slightly more delicate than just updating a few dependencies.

Afaik, and please correct me if I'm wrong, there is ongoing work on `1.0.0-wip` branch (well duh :) which uses `leveldown@~1.0.0` so merging that into master would take care of the problems with `leveldown` not working with io.js. Which is the key thing with io.js problems.

However, there's also ongoing work with removing `WriteStream` and replacing that with `level-ws` instead. But it's unclear to me if it's still going to be supported since it's a devDependency, which could potentially be removed?

`level-ws` also has its issues because it devDepends on `level`.

**Comment by ralphtheninja** [comment]
https://github.com/iojs/io.js/issues/456

**Comment by jesstelford** [comment]
For anyone else who comes across this, the current workaround is to remove the `level` package from your dependencies, then install the `1.0.0-wip` branch of `levelup` along with the latest version of `leveldown`:

    npm install --save rvagg/node-levelup#1.0.0-wip leveldown

Then in your source, change instances of `var level = require('level')` to `var level = require('levelup')`

**Comment by ralphtheninja** [comment]
:+1:

**Comment by jesstelford** [comment]
@ralphtheninja To clarify; is this closed as it's now working?

**Comment by mcollina** [comment]
Yes, `leveldown@0.10.4` works fine in both 0.12 and iojs. See https://github.com/rvagg/node-leveldown/pull/146.

**Comment by jesstelford** [comment]
Hurray! :D

**Comment by ralphtheninja** [comment]
@jesstelford Yes, sorry I wasn't clear :)
