### ISSUE TITLE
c

### ISSUE THREAD

**Issue by loveencounterflow** [rvagg/node-levelup#325]

**Comment by dominictarr** [comment]
please add a issue description I have _no idea_ what this is about

**Comment by loveencounterflow** [comment]
this is about me being overworked and mindlessly going from issue to issue then at some point hitting the wrong button and in a "o noes" splitsecond inadvertantly creating a useless issue...

i tried to remove it but i seemingly cannot even if it's open by me and as yet uncommented.

i then went to sleep.

**Comment by juliangruber** [comment]
we can only close it

**Comment by juliangruber** [comment]
oops what happened there

**Comment by loveencounterflow** [comment]
is someone else overworked?

**Comment by juliangruber** [comment]
not currently :P
